### ISSUE TITLE
Add package-lock.json to the repository to allow stable and reproducible builds

### ISSUE THREAD

**Issue by aschleifer** [aliyun/alibabacloud-resourcify-cli#67]
When nodejs / npm installs dependencies, it auto-generates a [`package-lock.json`](https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json). This file holds the exact information which version of each dependency was installed and the application was tested under.

It is used during the normal `npm install` call to re-install exactly these versions again. The purpose is to have a deterministic build and to be sure that the product is installed with the dependencies that the developer has tested it against.

It is therefor also needed to create [reproducible builds](https://reproducible-builds.org/) which is quickly getting a standard and requirement for many Linux distributions as they also create a chain of trust for users of that distribution when installing a package that is reproducible.

Yes, without the file any user who installs this package will get always the latest dependencies, but in order for this to work, everyone would need to honor [semantic versioning](https://semver.org) which aliyun isn't too good to do themselves, as can be seen in https://github.com/aliyun/aliyun-cli/issues/327 where suddenly in a minor version a feature breaks.

Also without the log files any user who installs this library will not see when updates to dependencies are coming out as he would have to forcibly reinstall the software periodically to get updates.

With the lock file, the product developers would have to
- update the dependencies
- test and make sure the product still works with the new dependency versions
- push a new version of their tool out

Then the users would see this new version and can update their installation.

Another advantage of adding the `package-lock.json` to the repository is that you can configure github to scan the file and alert you for possible vulnerabilities: https://docs.github.com/en/github/managing-security-vulnerabilities/about-alerts-for-vulnerable-dependencies#dependabot-alerts-for-vulnerable-dependencies

As a final point adding such a lock file is not unique to nodejs/npm. All major languages have such a logic and encourage the developers to add the file to the  repository. E.g. rust, python, go, php, ...

**Comment by JacksonTian** [comment]
Hi @aschleifer , The package-lock.json is added into repository now.

**Comment by anthraxx** [comment]
@JacksonTian thank you very much, this is a warm and welcoming change :cat:

**Comment by JacksonTian** [comment]
I close the issue. Any questions, feel free to re-open it. Thank you again.
