### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by aschleifer** [aliyun/alibabacloud-resourcify-cli#68]
In order to use this cli properly in our deployment systems we need to be able to configure it with environment variables.

[The old cli](https://github.com/aliyun/aliyun-cli) had the support to set the access key and and access secret in order to tell the cli with which alicloud account to interact. We would need the same logic to use the new CLI.

The only way the CLI [currently has for configuration it](https://github.com/aliyun/alibabacloud-resourcify-cli#arc-configuration) is to configure it via some commands which would require us to pass the critical information (access secret) as command line parameter which is very insecure, as it is then globally visible in procfs.

A nice benefit of support environment variables would be that this tool could than be compatible to https://github.com/arafato/alicloud-vault as the previous aliyun cli also was.

**Comment by JacksonTian** [comment]
Hi @aschleifer , this issue was fixed in #69 .

**Comment by anthraxx** [comment]
I think it would also make sense to have `ALICLOUD_REGION_ID` supported. I can make a pull request if you wish.

**Comment by JacksonTian** [comment]
@anthraxx thank you.
