### ISSUE TITLE
感觉这里的中英文不太匹配，是不是可以改进下。

### ISSUE THREAD

**Issue by JacksonTian** [aliyun/alibabacloud-resourcify-cli#7]
感觉这里的中英文不太匹配，是不是可以改进下。
中文是说获取一个文件，英文是说获取代理以访问API服务。
另外 get-agent 为什么变成 obtain an agent 了。

_Originally posted by @AxiosCros in https://github.com/aliyun/alibabacloud-resourcify-cli/pull/6#r505134048_

**Comment by night556** [comment]
具体为啥这么写有点忘了，但总共只有两个渠道，一个来源于官网文档，一个就是来源于谷歌翻译。后面我会再看一看这个地方

**Comment by AxiosCros** [comment]
谷歌的机翻有点坑，比如这个 obtain，虽然也有“获取“的意思，但是更多的意思是通过某些努力后的那种”获得“，一般的”获取“应该是 get
