### ISSUE TITLE
[Feature Request] Support --assume-role in config

### ISSUE THREAD

**Issue by daxingplay** [aliyun/alibabacloud-resourcify-cli#75]
Please support RAM role in config like aliyun-cli:

https://help.aliyun.com/document_detail/121259.html#title-j1z-nj4-q1d

Maybe like this:
```
arc-config --access-key-id=xxxx --access-key-secret=xxxx --assume-role=acs:ram::xxxx:role/xxxx --role-session-name=xxxx
```

**Comment by JacksonTian** [comment]
推荐用 acc 工具来完成统一的 credentials 配置了。https://github.com/aliyun/alibabacloud-credentials-cli
